"""initial commercial schema

Revision ID: 43b3180ac4fc
Revises: 
Create Date: 2026-09-16 18:09:10.057215

"""
from alembic import op
import sqlalchemy as sa
import app.models.base


# revision identifiers, used by Alembic.
revision = '43b3180ac4fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('audit_events',
    sa.Column('tenant_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_event_tenant_created_at', ['tenant_id', 'created_at'], unique=False)

    op.create_table('datasets',
    sa.Column('tenant_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_dataset_tenant_name')
    )
    op.create_table('models',
    sa.Column('tenant_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_model_tenant_name')
    )
    op.create_table('monitoring_alerts',
    sa.Column('tenant_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_entity_type', sa.String(length=100), nullable=True),
    sa.Column('source_entity_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name='ck_monitoring_alert_severity'),
    sa.CheckConstraint("status IN ('open', 'acknowledged', 'resolved')", name='ck_monitoring_alert_status'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_alerts', schema=None) as batch_op:
        batch_op.create_index('ix_monitoring_alert_tenant_created_at', ['tenant_id', 'created_at'], unique=False)

    op.create_table('users',
    sa.Column('tenant_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_user_tenant_email')
    )
    op.create_table('audit_integrity_checks',
    sa.Column('tenant_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('checked_from_event_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column('checked_to_event_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['checked_from_event_id'], ['audit_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['checked_to_event_id'], ['audit_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_integrity_checks', schema=None) as batch_op:
        batch_op.create_index('ix_audit_integrity_check_tenant_created_at', ['tenant_id', 'created_at'], unique=False)

    op.create_table('dataset_versions',
    sa.Column('dataset_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('uri', sa.String(length=500), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('schema', sa.JSON(), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'version', name='uq_dataset_version_dataset_version')
    )
    op.create_table('user_roles',
    sa.Column('tenant_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('user_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('role_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('model_versions',
    sa.Column('model_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('artifact_uri', sa.String(length=500), nullable=False),
    sa.Column('training_dataset_version_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('approved_by', app.models.base.GUID(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'approved', 'deployed', 'archived')", name='ck_model_version_status'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_dataset_version_id'], ['dataset_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'version', name='uq_model_version_model_version')
    )
    op.create_table('decisions',
    sa.Column('tenant_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('model_version_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('application_reference', sa.String(length=255), nullable=False),
    sa.Column('request_id', sa.String(length=255), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("outcome IN ('approve', 'refer', 'decline')", name='ck_decision_outcome'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'request_id', name='uq_decision_tenant_request_id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index('ix_decision_tenant_created_at', ['tenant_id', 'created_at'], unique=False)

    op.create_table('fairness_evaluations',
    sa.Column('tenant_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('model_version_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('protected_attribute', sa.String(length=100), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fairness_evaluations', schema=None) as batch_op:
        batch_op.create_index('ix_fairness_evaluation_tenant_created_at', ['tenant_id', 'created_at'], unique=False)

    op.create_table('model_deployments',
    sa.Column('tenant_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('model_version_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('deployed_by', app.models.base.GUID(length=36), nullable=True),
    sa.Column('previous_deployment_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'rolled_back')", name='ck_model_deployment_status'),
    sa.ForeignKeyConstraint(['deployed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['previous_deployment_id'], ['model_deployments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_deployments', schema=None) as batch_op:
        batch_op.create_index('ix_model_deployment_tenant_created_at', ['tenant_id', 'created_at'], unique=False)

    op.create_table('explanations',
    sa.Column('decision_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('base_value', sa.Float(), nullable=False),
    sa.Column('feature_attributions', sa.JSON(), nullable=False),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id')
    )
    op.create_table('governance_results',
    sa.Column('decision_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('check_name', sa.String(length=100), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('governance_results', schema=None) as batch_op:
        batch_op.create_index('ix_governance_result_decision_id', ['decision_id'], unique=False)

    op.create_table('review_cases',
    sa.Column('tenant_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('decision_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('assigned_to', app.models.base.GUID(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('open', 'in_review', 'closed')", name='ck_review_case_status'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_cases', schema=None) as batch_op:
        batch_op.create_index('ix_review_case_tenant_created_at', ['tenant_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_cases', schema=None) as batch_op:
        batch_op.drop_index('ix_review_case_tenant_created_at')

    op.drop_table('review_cases')
    with op.batch_alter_table('governance_results', schema=None) as batch_op:
        batch_op.drop_index('ix_governance_result_decision_id')

    op.drop_table('governance_results')
    op.drop_table('explanations')
    with op.batch_alter_table('model_deployments', schema=None) as batch_op:
        batch_op.drop_index('ix_model_deployment_tenant_created_at')

    op.drop_table('model_deployments')
    with op.batch_alter_table('fairness_evaluations', schema=None) as batch_op:
        batch_op.drop_index('ix_fairness_evaluation_tenant_created_at')

    op.drop_table('fairness_evaluations')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index('ix_decision_tenant_created_at')

    op.drop_table('decisions')
    op.drop_table('model_versions')
    op.drop_table('user_roles')
    op.drop_table('dataset_versions')
    with op.batch_alter_table('audit_integrity_checks', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_integrity_check_tenant_created_at')

    op.drop_table('audit_integrity_checks')
    op.drop_table('users')
    with op.batch_alter_table('monitoring_alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_monitoring_alert_tenant_created_at')

    op.drop_table('monitoring_alerts')
    op.drop_table('models')
    op.drop_table('datasets')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_event_tenant_created_at')

    op.drop_table('audit_events')
    op.drop_table('tenants')
    op.drop_table('roles')
    # ### end Alembic commands ###
