"""add outbox events table

Revision ID: dd4af7b08b9d
Revises: a4e71d2b014c
Create Date: 2026-09-17 11:05:02.234876

"""
from alembic import op
import sqlalchemy as sa
import app.models.base


# revision identifiers, used by Alembic.
revision = 'dd4af7b08b9d'
down_revision = 'a4e71d2b014c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('tenant_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'published', 'failed')", name='ck_outbox_event_status'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.create_index('ix_outbox_event_status_created_at', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_outbox_event_tenant_created_at', ['tenant_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.drop_index('ix_outbox_event_tenant_created_at')
        batch_op.drop_index('ix_outbox_event_status_created_at')

    op.drop_table('outbox_events')
    # ### end Alembic commands ###
